#!/usr/bin/env sh
STACK_PATH=$(pwd)
PROJECT_PATH=$(pwd)

set -ae

. "${STACK_PATH}/.env.dist" # default settings
if [ -f "${STACK_PATH}/.env" ]; then
    . "${STACK_PATH}/.env" # custom *global* settings
elif [ -f "${PROJECT_PATH}/.env" ]; then
    . "${PROJECT_PATH}/.env" # custom *local* settings
fi

if [ "path" = "${1}" ]; then
    echo "Stack path: ${STACK_PATH}"
    echo "Project path: ${PROJECT_PATH}"

    exit
fi

if [ "ps" = $1 ] || [ "ls" = $1 ]; then
    docker ps | grep opencodeco
    exit
fi

if [ "network" = $1 ]; then
    NET=$(docker network ls | grep opencodeco)

    if [ -z "$NET" ]; then
	echo "OpenCodeCo network not found. Creating one..."
	docker network create opencodeco
	echo "🕸️ Done!"
    else
	echo "🕸️ OpenCodeCo network already exists!"
    fi
    
    exit
fi

COMPONENT=$STACK_PATH/$1

if [ ! -d $COMPONENT ]; then
    echo "\033[0;31mWhoops! Component \"$COMPONENT\" does not exists." >&2
    exit 1
fi

CMD=${@:2}
docker-compose -f $COMPONENT/docker-compose.yml ${CMD:-up -d}
