#!/usr/bin/env sh
STACK_PATH=$(pwd)

set -ae

source "$STACK_PATH/.env.dist"
if [ -f "$STACK_PATH/.env" ]; then
    source "$STACK_PATH/.env"
fi

if [ "path" = $1 ]; then
    echo $STACK_PATH
    exit
fi

if [ "ps" = $1 ] || [ "ls" = $1 ]; then
    docker ps | grep opencodeco
    exit
fi

if [ "network" = $1 ]; then
    NET=$(docker network ls | grep opencodeco)

    if [ -z "$NET" ]; then
	echo "OpenCodeCo network not found. Creating one..."
	docker network create opencodeco
	echo "🕸️ Done!"
    else
	echo "🕸️ OpenCodeCo network already exists!"
    fi
    
    exit
fi

COMPONENT=$STACK_PATH/$1

if [ ! -d $COMPONENT ]; then
    echo "\033[0;31mWhoops! Component \"$COMPONENT\" does not exists." >&2
    exit 1
fi

CMD=${@:2}
docker-compose -f $COMPONENT/docker-compose.yml ${CMD:-up -d}
