receivers:
  jaeger:
    protocols:
      thrift_http:
      thrift_binary:
  statsd:
    endpoint: 0.0.0.0:8125
    is_monotonic_counter: true
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:9090
  otlp/jaeger:
    endpoint: opencodeco-jaeger:4317
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp, jaeger]
      exporters: [logging, otlp/jaeger]
    metrics:
      receivers: [otlp, statsd]
      exporters: [logging, prometheus]
