services:
  opencodeco-mysql:
    container_name: opencodeco-mysql
    image: mysql:9.3
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: opencodeco
    volumes:
      - opencodeco-mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-popencodeco"]
      interval: 10s
      timeout: 5s
      retries: 5

  opencodeco-phpmyadmin:
    container_name: opencodeco-phpmyadmin
    image: phpmyadmin:5.2
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=opencodeco-mysql
    depends_on:
      opencodeco-mysql:
        condition: service_healthy
      
networks:
  default:
    name: opencodeco
    external: true
      
volumes:
  opencodeco-mysql:
    name: opencodeco-mysql
